apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-js
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.js.wiki/
      helm:
        chart: wiki
        valueFiles:
          - $wikijs/values.yaml # Path to your values file in the repo
    - repoURL: https://github.com/kvtomino/argocd.git
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
