apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-js
  namespace: argocd
spec:
  destination:
    namespace: wiki
    name: wikijs
  project: default
  sources:
    - Chart: wiki
      repoURL: https://charts.js.wiki/
      targetRevision: 2.2.20
      helm:
        valueFiles:
          - $wikijs/values.yaml # Path to your values file in the repo
    - repoURL: 'https://github.com/kvtomino/argocd'
      targetRevision: HEAD
      ref: values