apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-js-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.js.wiki
    helm:
      chart: wiki
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki