apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-js
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.js.wiki
    helm:
      chart: wiki
      valueFiles:
      - values.yaml  # Path to your values file
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
