postgresql:
  enabled: true
  postgresqlDatabase: wiki
  postgresqlUsername: postgress
  postgresqlPassword: Brussel01
  persistence:
    enabled: true
    size: 15Gi
    storageClass: "vsan-block-sc"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: wiki.fistik.be
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wiki-tls-secret
      hosts:
        - wiki.fistik.be

nodeSelector:
  kubernetes.io/role: worker

tolerations: []

affinity: {}
