postgresql:
  postgresqlUser: postgres
  existingSecret: wiki-js-postgresql-secret
  existingSecretKey: postgresql-password
  persistence:
    enabled: true
    existingclaim: wikijspv
    size: 15Gi
