postgresql:
  postgresqlUser: wiki-js
  existingSecret: wiki-js-postgresql-secret
  existingSecretKey: postgresql-password
  persistence:
    enabled: true
    size: 15Gi
    storageClass: "vsan-block-sc"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: wiki.fistik.be
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wiki-tls-secret
      hosts:
        - wiki.fistik.be
